AWSTemplateFormatVersion: 2010-09-09
Description: This is for cats.
  
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  TolgaCloudFormationInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: karaoglan2
      SecurityGroups:
        - HTTPandSSH
      Tags:
        - Key: Name
          Value: TolgaCloudFormation
      UserData: 
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           yum update -y
           yum install -y httpd.x86_64
           systemctl start httpd.service
           systemctl enable httpd.service
           usermod -a -G apache ec2-user
           chown -R ec2-user:apache /var/www
           chmod -R 777 /var/www/html
           cd /var/www/html/
           wget https://raw.githubusercontent.com/fatihseydi/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
           wget https://raw.githubusercontent.com/fatihseydi/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
           wget https://raw.githubusercontent.com/fatihseydi/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
           wget https://raw.githubusercontent.com/fatihseydi/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
           systemctl restart httpd
  
Transform:
  
Outputs: